### PR TITLE
Add neovim's LSP

### PR DESCRIPTION
**Pull request by p00f**

### CODE REVIEW

**Comment by p00f** [comment]
@MindTooth

**Comment by p00f** [comment]
Also, what do you think about changing `Nontext` to xgray2 or xgray3?

**Comment by MindTooth** [comment]
> Also, what do you think about changing `Nontext` to xgray2 or xgray3?

I think that we keep the changes to a minimum now.  Already added a bit.  We can discuss the `NonText` part on Discord.

Care to post a screenshot showing the changes?

**Comment by p00f** [comment]
sure

**Comment by p00f** [comment]
warning - 
image
error - 
image
info - 
image
i'll change hint

**Comment by p00f** [comment]
I changed both hint and info (hint should be more prominent than info)
image

**Comment by MindTooth** [comment]
Care to show a bit more context of that last screenshot?  It's a bit flashy.  To me, the cyan doesn't reflect an error if you know what I mean.

Also, I'm unable to really test this since I don't use 0.5 of NeoVim.  I'll see if I can test it out myself soon.

Here you can see my current one with `vim-lsp`:
Screen Shot 2020-12-15 at 12 03 04

**Comment by p00f** [comment]
error(x mark in sign column) is bright_red, warning(exclamation mark in sign column) is bright_yellow, info(i in sign column) is bright_green and hint(light bulb) is bright_cyan.

I think yours is better, with white fg and red bg for error - makes errors noticeable.

**Comment by MindTooth** [comment]
I'll merge it for now.  Hopefully, I get to test it when 0.5 is released. 👍🏻 

Thanks. ❤️

**Pull request merged**
