### PR TITLE
ci: run lint job on pull requests

### PR DESCRIPTION
**Pull request by MindTooth**
Should now be able to track incoming changes for any errors.

---

Stole it from here: https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

### CODE REVIEW

**Comment by MindTooth** [comment]
Hmm.  This did not in fact trigger a pipeline. 🤔  No constraint on file types, so it should have.

**Review by roosta — APPROVED** [review]
Yeah, should for sure run on PR's

**Comment by roosta** [comment]
Oh, it didn't trigger. Hmm

**Comment by MindTooth** [comment]
Works now.  But, thoughts on switching to https://github.com/reviewdog/action-vint instead?

**Comment by roosta** [comment]
Yeah, much preferable I think, didn't know there was an action for that

**Comment by MindTooth** [comment]
Hmm.  It works, but the pipeline succeeded with an error posted?  Perhaps that must happen for this to work. 🤔

**Comment by roosta** [comment]
Hmm, I also expected it to fail, but I suppose this will work just as well, if not better.

**Comment by roosta** [comment]
https://github.com/reviewdog/action-vint/issues/6

**Comment by MindTooth** [comment]
Tried `failure`, ref.: https://github.com/reviewdog/reviewdog#exit-codes

But does not work. 🤔

**Comment by roosta** [comment]
try setting it to `error`
> (optional. same as -level flag. [info,warning,error])

**Comment by MindTooth** [comment]
I think `error` is the default.  My suspicion is that this action does not take into account the exist code.

**Comment by MindTooth** [comment]
Personally I'm fine with having the old setup, but just making sure pull requests are included.  Thoughts?

**Comment by roosta** [comment]
Agreed, seems it the action doesn't work quite like we expected. If you can get the old one on prs that'd be perfect.

**Pull request merged**
