### PR TITLE
Complete README.md list of supported plugins.

### PR DESCRIPTION
**Pull request by micangl**
Completes the list of supported plugins in the README.md.

### CODE REVIEW

**Comment by micangl** [comment]
Sorry for all the commits. I forked from the wrong branch.

**Comment by MindTooth** [comment]
Thanks. 🤘🏻  Care to sort them alphabetically?

**Comment by micangl** [comment]
Sorry, hadn't noticed the alphabetical ordering.

**Comment by MindTooth** [comment]
Thank you. ☺️

**Pull request merged**
