### PR TITLE
Change search/incsearch to use fg none, bright_black background, bold/underline

### PR DESCRIPTION
**Pull request by roosta**
I think the magenta is a bit much, I was messing around earlier in the emacs theme develop branch and came up with this. Thoughts @MindTooth ?

### CODE REVIEW

**Comment by MindTooth** [comment]
I like the idea of chaning the highlight, as I've myself found the magenta a bit strong.  However, with this change, it might not be strong enough.

Off to bed, so I have no clever suggestions atm.  But I like the idea of a change.

### New
screen shot 2018-07-18 at 23 51 06

### Old
screen shot 2018-07-18 at 23 51 41

**Comment by roosta** [comment]
Yeah I agree it might not be strong enough. 
I like the idea of not discarding syntax color when a search is highlighted though, the same reason I added the option to invert search but that was somewhat unsuccessful since it cause problems with my cursor and visually selecting something that is already highlighted.
I'll give it a think and see if I can't figure something out.

**Comment by roosta** [comment]
Had another go at it. Did a force push so the branch needs to be reset. Think this works better.
preview

**Comment by MindTooth** [comment]
Looks much better 👍🏻  Nice job.

**Comment by roosta** [comment]
Thanks

**Pull request merged**
