### PR TITLE
Adds installation instructions for Vim 8's native plugin.

### PR DESCRIPTION
**Pull request by xfbs**
I guess this might be useful to some people. I didn't know Vim could do that!

### CODE REVIEW

**Comment by MindTooth** [comment]
Sweet..  One for the minimalistic people out there.

Is that path hardcoded for Vim by deafult?

**Comment by xfbs** [comment]
There is some documentation about this in vim, which you can find under `:help pack-add`. 

Basically it loads all plugins that are in `~/.vim/pack/*/start` on startup, and all plugins in ~/.vim/pack/*/opt` you can explicitly load by putting

```vim
packadd pluginname
```

In your vimrc. You don't need this for colorschemes tho. So if srcery is in ~/.vim/pack/default/opt/srcery`, you can just do `colorscheme srcery` and it'll find it. 

Amazing that vim can do this right? I don't need to use pathogen anymore!

**Comment by MindTooth** [comment]
Would it be more relevant to use `~/.vim/pack/colors/opt/srcery` maybe?

I'm not there yet.  Using `dein.vim` and have far to many plugins... 🤣

**Comment by MindTooth** [comment]
I'll more for now.

Thank you for your PR. ❤️

**Pull request merged**
