### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by roosta**
Here are some tweaks I'd like some input on, seems I'm on a bit of a blue streak, but I think it works better, especially on the `SpecialKey`, don't know why I thought the old color was a good idea. The blue on `PmenuSel` I think sticks out less as well.
tweaks_preview

### CODE REVIEW

**Comment by roosta** [comment]
The special key color was chosen because that's what vanilla vim defaults to. It also doesn't conflict with any other internal vim highlight.

**Comment by MindTooth** [comment]
Totally okay with the new blue.  The pink can stand out a bit too much at times. 😉 

LGMT. 👍🏻

**Comment by McSinyx** [comment]
I've just pulled after ages and realized that SpecialKey is also used for listchars (nbsp, space, tab and trail), so maybe that's why previously it was gray:

2020-12-22T13:37:29

**Comment by roosta** [comment]
I don't have that issue. Just to be clear I did this
```
:set listchars+=space:.
:set list
```
This is the result:
image

@MindTooth mentioned on the discord channel that indent guides also use `SpecialKey`, resulting in blue highlighting.

Is there a hl group that can be set that handles listchars other than `SpecialKey`, couldn't find any. Vanilla vim also uses a blue color IIRC, is there a similar issue when running vim without a config?

**Comment by McSinyx** [comment]
@roosta, I can't reproduce the grey spaces with your config.  [Here is my current vimrc.](https://git.sr.ht/~cnx/dotfiles/tree/bfd59f83b7af16541e8b70c1321470c65131ae29/item/vim/.vim/vimrc#L10)  Regarding SpecialKey, it seems to be [hardcoded in Vim](https://github.com/vim/vim/blob/fa79be6b10e1d34fd697a56e85f6c0ce101f3d62/src/gui_beval.c#L716), so I don't think there is any other group of that effect.

Vanilla Vim has SpecialKey in Cyan and NonText in Blue.  At this moment I'm patching srcery with SpecialKey back to XGray4 since I almost never have to see keymaps.

**Comment by roosta** [comment]
I thought it was supposed to use the group `NonText`, when I remove that from srcery-vim my spaces revert to blue. Not sure why this isn't the case for you.

**Comment by MindTooth** [comment]
Screen Shot 2020-12-22 at 15 02 17

Now I remember.  I manually needed to change the highlight group to `Comment` to have them return back to gray.  I'm using [IndentLine](https://github.com/Yggdroot/indentLine).

From the docs:
> <	|hl-NonText| highlighting will be used for "eol", "extends" and
	"precedes". |hl-Whitespace| for "nbsp", "space", "tab" and "trail".

**Comment by roosta** [comment]
@MindTooth nice that is has a config opt to set which group it uses.

I see there's a hl group called `Whitespace`, and that's also set to `SrceryXgray4` as far as I can tell

**Comment by McSinyx** [comment]
> |hl-Whitespace| for "nbsp", "space", "tab" and "trail".

Strange, the one on vimhelp and my local version reads

> "SpecialKey" for "nbsp", "space", "tab" and "trail".

I suppose I'm using a more recent Vim version (8.2.1913 on Debian Sid).

**Comment by MindTooth** [comment]
vimhelp.org is the latest from source dated 10 October 2020.  Strange they would be different. 🤔

**Comment by roosta** [comment]
I was testing in neovim, my bad. It apparently handles whitespace different from regular vim. When I change to regular vim I see the same behaviour as you @McSinyx 

I don't really have a fix for this, setting `SpecialKey` to xgray is not ideal in my opinion. Any suggestions?

**Comment by roosta** [comment]
I'm running vim version 8.2.1989

**Comment by McSinyx** [comment]
> Any suggestions?

Unfortunately, no.  I can keep the one-line patch locally just fine, and this discussion is enough for any future user stumbling upon the issue.  The best thing we can do IMHO is to file an issue over Vim, if it is not already filed.

**Comment by roosta** [comment]
It has probably been discussed, I suspect neovim made a change to address this
> |hl-NonText| highlighting will be used for "eol", "extends" and
> "precedes". |hl-Whitespace| for "nbsp", "space", "tab" and "trail".

**Pull request merged**
